loader:
  class: STOIC2021ForMuCoDiStudent
data:
  train_json: ${oc.env:REPO_ROOT}/data/evaluation/stoic2021_jsonl/train.jsonl
  valid_json: ${oc.env:REPO_ROOT}/data/evaluation/stoic2021_jsonl/dev.jsonl
  test_json: ${oc.env:REPO_ROOT}/data/evaluation/stoic2021_jsonl/test.jsonl
img_paths_key: nii_path
modality: chest_ct
