loader:
  class: NiftiForCTClip
data:
  train_json: ${oc.env:REPO_ROOT}/data/evaluation/coca_gated_jsonl/train.jsonl
  valid_json: ${oc.env:REPO_ROOT}/data/evaluation/coca_gated_jsonl/dev.jsonl
  test_json: ${oc.env:REPO_ROOT}/data/evaluation/coca_gated_jsonl/test.jsonl
img_paths_key: nii_path
modality: chest_ct
ctclip_upstream_dir: ${oc.env:REPO_ROOT}/scripts/external/CT-CLIP
